### ISSUE TITLE
color model not working?

### ISSUE THREAD

**Issue by mivanit** [bnanes/shrink-pdf#2]
This program has worked for me before but for some reason it is giving me rather strange output on these specific pdfs.
[earth114_lect02.pdf](https://github.com/bnanes/shrink-pdf/files/4589469/earth114_lect02.pdf)
[earth114_lect02_SHRUNK.pdf](https://github.com/bnanes/shrink-pdf/files/4589473/earth114_lect02_SHRUNK.pdf)

I'm using the tool to compress lecture slides from all my past classes, so I don't have the source files. It has seemed to work fine for all my other classes.

**Comment by bnanes** [comment]
I think it's an issue with handling transparency. I'll look into it.

**Comment by bnanes** [comment]
The [beta-5 release](https://github.com/bnanes/shrink-pdf/releases/tag/beta-5) contains a partial fix for this issue.

Because the jpeg image format typically does not support transparency, images containing transparency as an alpha channel, mask, or translucency setting will loose transparency during the conversion process. While the Java Image I/O API, used by PDF Shrinker for jpeg encoding, will include transparency information as an alpha channel, most other applications do not read these images properly. See [this Open JDK bug report](https://bugs.openjdk.java.net/browse/JDK-4836466) for more information.

As a partial fix for this issue, PDF Shrinker beta-5 release will remove any transparency information prior to jpeg encoding. While usefulness of this procedure will depend on the particular image, colored casts produced in prior versions should no longer be present. Note that this procedure does not blend transparent images with underlying document components, a feature which is beyond the scope of this software.
